---
- name: Install Java 17
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Display ansible_distribution
      debug:
        msg: "The distribution is: {{ ansible_distribution }}"

    - name: Install Java 17 on Ubuntu and Debian
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Install Java 17 on CentOS, Red Hat, or Fedora
      dnf:
        name: java-17-openjdk-devel
        state: present
      when: ansible_distribution in ["CentOS", "RedHat", "Fedora"]

    - name: Ensure Java 17 is installed
      command: java -version
      register: java_version

    - name: Display Java 17 version
      debug:
        msg: "Java 17 version: {{ java_version.stdout }}"
