---
- name: Install Apache2
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Display ansible_distribution
      debug:
        msg: "The distribution is: {{ ansible_distribution }}"

    - name: Install Apache2 on Ubuntu and Debian
      apt:
        name: apache2
        state: present
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Install Apache on CentOS, Red Hat, or Fedora
      dnf:
        name: httpd
        state: present
      when: ansible_distribution in ["CentOS", "RedHat", "Fedora"]

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Ensure Apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution in ["CentOS", "RedHat", "Fedora"]
